import bcrypt from 'bcryptjs';
import User from '../models/user';
import Product from '../models/product.model';

const catalogSeed = [
    {
        slug: 'iphone-16-pro-max-256gb',
        name: 'iPhone 16 Pro Max 256GB',
        brand: 'Apple',
        category: 'Điện thoại',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',
        price: 30990000,
        oldPrice: 34490000,
        discount: 10,
        soldCount: 980,
        rating: 4.9,
        shortDescription: 'Flagship chip mới, camera tele nâng cấp, pin tốt hơn.',
        isPromotion: true,
        isLatest: true,
        isBestSeller: true,
    },
    {
        slug: 'samsung-galaxy-s25-ultra-256gb',
        name: 'Samsung Galaxy S25 Ultra 256GB',
        brand: 'Samsung',
        category: 'Điện thoại',
        image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=900&q=80',
        price: 26990000,
        oldPrice: 31990000,
        discount: 15,
        soldCount: 870,
        rating: 4.8,
        shortDescription: 'Bút S-Pen tích hợp, màn hình lớn, camera zoom xa.',
        isPromotion: true,
        isLatest: true,
        isBestSeller: true,
    },
    {
        slug: 'xiaomi-15-pro-5g',
        name: 'Xiaomi 15 Pro 5G',
        brand: 'Xiaomi',
        category: 'Điện thoại',
        image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=900&q=80',
        price: 18990000,
        oldPrice: 21590000,
        discount: 12,
        soldCount: 710,
        rating: 4.7,
        shortDescription: 'Hiệu năng mạnh, camera Leica, sạc nhanh công suất cao.',
        isPromotion: true,
        isLatest: true,
        isBestSeller: false,
    },
    {
        slug: 'oppo-find-x8',
        name: 'OPPO Find X8',
        brand: 'OPPO',
        category: 'Điện thoại',
        image: 'https://images.unsplash.com/photo-1598327105854-8b0d4d6b3f73?auto=format&fit=crop&w=900&q=80',
        price: 17990000,
        oldPrice: 19590000,
        discount: 8,
        soldCount: 620,
        rating: 4.6,
        shortDescription: 'Thiết kế cao cấp, màn hình mượt và camera chân dung đẹp.',
        isPromotion: true,
        isLatest: false,
        isBestSeller: false,
    },
    {
        slug: 'macbook-air-m4-13-inch',
        name: 'MacBook Air M4 13 inch',
        brand: 'Apple',
        category: 'Laptop',
        image: 'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80',
        price: 29990000,
        oldPrice: 31990000,
        discount: 6,
        soldCount: 430,
        rating: 4.9,
        shortDescription: 'Laptop mỏng nhẹ, pin dài, phù hợp học tập và công việc.',
        isPromotion: false,
        isLatest: true,
        isBestSeller: true,
    },
    {
        slug: 'ipad-pro-m4-11-inch',
        name: 'iPad Pro M4 11 inch',
        brand: 'Apple',
        category: 'Tablet',
        image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80',
        price: 26990000,
        oldPrice: 28990000,
        discount: 7,
        soldCount: 390,
        rating: 4.8,
        shortDescription: 'Màn hình đẹp, hiệu năng cao, đa nhiệm tốt cho creator.',
        isPromotion: false,
        isLatest: true,
        isBestSeller: false,
    },
    {
        slug: 'asus-rog-zephyrus-g16',
        name: 'ASUS ROG Zephyrus G16',
        brand: 'ASUS',
        category: 'Laptop Gaming',
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80',
        price: 48990000,
        oldPrice: 51990000,
        discount: 5,
        soldCount: 250,
        rating: 4.7,
        shortDescription: 'Laptop gaming cao cấp, tản nhiệt tốt, màn hình tần số quét cao.',
        isPromotion: false,
        isLatest: true,
        isBestSeller: false,
    },
    {
        slug: 'dell-xps-14-9440',
        name: 'Dell XPS 14 9440',
        brand: 'Dell',
        category: 'Laptop',
        image: 'https://images.unsplash.com/photo-1593642634367-d91a135587b5?auto=format&fit=crop&w=900&q=80',
        price: 42990000,
        oldPrice: 45990000,
        discount: 6,
        soldCount: 220,
        rating: 4.8,
        shortDescription: 'Ultrabook sang trọng, hiệu năng ổn định cho dân văn phòng.',
        isPromotion: false,
        isLatest: true,
        isBestSeller: false,
    },
    {
        slug: 'airpods-pro-2-usb-c',
        name: 'AirPods Pro 2 USB-C',
        brand: 'Apple',
        category: 'Tai nghe',
        image: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80',
        price: 5490000,
        oldPrice: 6290000,
        discount: 13,
        soldCount: 1280,
        rating: 4.9,
        shortDescription: 'Chống ồn chủ động tốt, âm thanh chi tiết, pin ổn định.',
        isPromotion: true,
        isLatest: false,
        isBestSeller: true,
    },
    {
        slug: 'apple-watch-series-10',
        name: 'Apple Watch Series 10',
        brand: 'Apple',
        category: 'Đồng hồ thông minh',
        image: 'https://images.unsplash.com/photo-1579586337278-3f436f25d4d6?auto=format&fit=crop&w=900&q=80',
        price: 9990000,
        oldPrice: 11490000,
        discount: 12,
        soldCount: 940,
        rating: 4.8,
        shortDescription: 'Theo dõi sức khỏe toàn diện, đồng bộ tốt với hệ sinh thái Apple.',
        isPromotion: true,
        isLatest: false,
        isBestSeller: true,
    },
    {
        slug: 'samsung-galaxy-buds3-pro',
        name: 'Samsung Galaxy Buds3 Pro',
        brand: 'Samsung',
        category: 'Tai nghe',
        image: 'https://images.unsplash.com/photo-1606400082777-ef05f3c5f89a?auto=format&fit=crop&w=900&q=80',
        price: 4290000,
        oldPrice: 4990000,
        discount: 14,
        soldCount: 810,
        rating: 4.7,
        shortDescription: 'Thiết kế gọn nhẹ, âm thanh sống động, chống ồn hiệu quả.',
        isPromotion: true,
        isLatest: false,
        isBestSeller: true,
    },
    {
        slug: 'anker-gan-prime-65w',
        name: 'Sạc nhanh Anker GaN Prime 65W',
        brand: 'Anker',
        category: 'Phụ kiện',
        image: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=80',
        price: 890000,
        oldPrice: 1190000,
        discount: 25,
        soldCount: 1520,
        rating: 4.8,
        shortDescription: 'Củ sạc nhỏ gọn, đa cổng, tối ưu cho điện thoại và laptop.',
        isPromotion: true,
        isLatest: false,
        isBestSeller: true,
    },
];

export const seedInitialData = async () => {
    const adminEmail = process.env.ADMIN_EMAIL || 'admin@smartzone.vn';
    const adminPassword = process.env.ADMIN_PASSWORD || '123456';

    const adminExisted = await User.findOne({ email: adminEmail.toLowerCase().trim() });
    if (!adminExisted) {
        const passwordHash = await bcrypt.hash(adminPassword, 10);

        await User.create({
            email: adminEmail.toLowerCase().trim(),
            password: passwordHash,
            firstName: 'Super',
            lastName: 'Admin',
            address: 'Ho Chi Minh',
            phoneNumber: '0900000000',
            gender: true,
            roleId: 'R1',
            positionId: 'P0',
            isActive: true,
        });
        console.log('Da seed tai khoan admin R1 mac dinh.');
    }

    const productOperations = catalogSeed.map((item) => ({
        updateOne: {
            filter: { slug: item.slug },
            update: { $set: item },
            upsert: true,
        },
    }));

    if (productOperations.length > 0) {
        const result = await Product.bulkWrite(productOperations, { ordered: false });
        const createdCount = Number(result?.upsertedCount || 0);
        const modifiedCount = Number(result?.modifiedCount || 0);
        console.log(`Da dong bo catalog san pham: them moi ${createdCount}, cap nhat ${modifiedCount}.`);
    }
};